name: Deploy Docs

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        working-directory: ./docs  # Replace with the correct directory path

      - name: Build
        run: npm run build
        working-directory: ./docs  # Replace with the correct directory path